# 👌🏻 Crear Dataset

In [5]:
import numpy as np
import pandas as pd

In [ ]:
numbers = np.arange(1, 101)

data = {
    "Num_1": np.repeat(numbers, len(numbers)),
    "Num_2": np.tile(numbers, len(numbers)),
    "addition": np.repeat(numbers, len(numbers)) + np.tile(numbers, len(numbers)),
    "subtraction": np.repeat(numbers, len(numbers)) - np.tile(numbers, len(numbers)),
    "multiplication": np.repeat(numbers, len(numbers)) * np.tile(numbers, len(numbers)),
    "division": np.round(np.repeat(numbers, len(numbers)) / np.tile(numbers, len(numbers)), 2)
}

In [21]:
df = pd.DataFrame(data)
df = pd.melt(df, id_vars = ["Num_1", "Num_2"],
             value_vars = ["addition", "subtraction", "multiplication", "division"],
             value_name = "Result",
             var_name = "Operation")

df.head()

Num_1  Num_2 Operation  Result
0      1      1  addition     2.0
1      1      2  addition     3.0
2      1      3  addition     4.0
3      1      4  addition     5.0
4      1      5  addition     6.0

In [24]:
operation_labels = {
    "addition": 0,
    "subtraction": 1,
    "multiplication": 2,
    "division": 3
}

df["Operation_label"] = df["Operation"].map(operation_labels)
df.head()

Num_1  Num_2 Operation  Result  Operation_label
0      1      1  addition     2.0                0
1      1      2  addition     3.0                0
2      1      3  addition     4.0                0
3      1      4  addition     5.0                0
4      1      5  addition     6.0                0

# 👀 ver informacion del dataset

In [22]:
df["Operation"].value_counts()

Operation
addition          10000
subtraction       10000
multiplication    10000
division          10000
Name: count, dtype: int64

In [25]:
df.describe()

Num_1         Num_2        Result  Operation_label
count  40000.000000  40000.000000  40000.000000     40000.000000
mean      50.500000     50.500000    663.467404         1.500000
std       28.866431     28.866431   1557.333307         1.118048
min        1.000000      1.000000    -99.000000         0.000000
25%       25.750000     25.750000      0.997500         0.750000
50%       50.500000     50.500000     49.000000         1.500000
75%       75.250000     75.250000    163.000000         2.250000
max      100.000000    100.000000  10000.000000         3.000000

In [26]:
df[df["Result"] == -99]

Num_1  Num_2    Operation  Result  Operation_label
10099      1    100  subtraction   -99.0                1

# 🥶 Seperar las caracteristicas de la variable objetivo 🎯

In [27]:
X = df[["Num_1", "Num_2", "Result"]].values
Y = df["Operation_label"].values

print(X.shape, Y.shape)
print(X)
print(Y)

(40000, 3) (40000,)
[[  1.     1.     2.  ]
 [  1.     2.     3.  ]
 [  1.     3.     4.  ]
 ...
 [100.    98.     1.02]
 [100.    99.     1.01]
 [100.   100.     1.  ]]
[0 0 0 ... 3 3 3]


# ⛏️ Dividir el dataset en entrenamiento y validacion

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

(32000, 3) (32000,)
(8000, 3) (8000,)


# 📝 Arquitectura del modelo